#!/usr/bin/perl -w
# $Id: p0rn-dbadd,v 1.5 2004-05-14 20:54:30 mitch Exp $
#
# add links to p0rn.db
#
# 2004 (C) by Christian Garbs <mitch@cgarbs.de>
# Licensed under GNU GPL.  See COPYING for details.

use strict;
use BerkeleyDB::Hash;
use P0rn::DB;

=head1 NAME

p0rn-dbadd - add links to the p0rn database

=head1 SYNOPSIS

B<p0rn-dbadd> I<table>

=head1 OVERVIEW

p0rn-dbadd adds links to the p0rn database.  There should be no need
to call this program directly.

=head1 DESCRIPTION

You must set the table name upon startup.  Existing database tables
are B<thumbz> for thumbnails, B<picz> for pictures and B<downz> for
download urls.  Links are then read from STDIN and saved to the
database.

=head1 DATA FORMAT

Format is one plain URL per line with no leading or trailing
whitespace.

Alternative format is a positive integer followed by a tab and a plain
URL per line.

=head1 FILES

All data is stored in a database.  By default, it is located in
B<./p0rn.db> (yes, that's the directory from which you're starting
p0rn-add).  Is you want to change this, set the environment variable
B<P0RNDBLOCATION> (the second letter is a zero) to another path and
filename.

=head1 SEE ALSO

L<p0rn-proxy(1)>, L<p0rn-download(1)>, L<p0rn-dbdump(1)>, L<p0rn-dbrestore(1)>

=head1 MODULES NEEDED

 use BerkeleyDB::Hash;

This module can be obtained at <F<http://www.cpan.org>>.

=head1 BUGS

Please report bugs by mail to <F<p0rn-bugs@cgarbs.de>>.

=head1 AUTHOR

p0rn-dbadd was written by Christian Garbs <F<mitch@cgarbs.de>>.

=head1 COPYRIGHT

p0rn-dbadd is licensed under the GNU GPL.

=cut

my $hash = opendb(shift);

while (my $line = <>) {
    chomp $line;
    $line =~ s/\?.*$//;
    my $value = 0;
    if ($line =~ /^(\d)+\t(.*)$/) {
	$value = $1;
	$line  = $2;
    }
    $hash->{$line} = $value;
}

untie %{$hash};


