#!/usr/bin/perl -w
# $Id: p0rn-dbadd,v 1.2 2004-05-11 15:57:49 mitch Exp $
#
# add contents to p0rn.db
#
use strict;
use BerkeleyDB::Hash;
use P0rn::DB;

my $hash = opendb(shift);

while (my $line = <>) {
    chomp $line;
    $line =~ s/\?.*$//;
    my $value = 0;
    if ($line =~ /^(\d)+\t(.*)$/) {
	$value = $1;
	$line  = $2;
    }
    $hash->{$line} = $value;
}

untie %{$hash};


