#!/usr/bin/perl -w
# $Id: p0rn-dbrestore,v 1.4 2005-10-14 18:17:12 mitch Exp $
#
# restores the complete p0rn.db
#
# 2004 (C) by Christian Garbs <mitch@cgarbs.de>
# Licensed under GNU GPL.  See COPYING for details.

use strict;

=head1 NAME

p0rn-dbrestore - restore the p0rn database

=head1 SYNOPSIS

B<p0rn-dbrestore>

=head1 OVERVIEW

p0rn-dbrestore reads a database backup from STDIN and writes it into
the p0rn database.

=head1 FILES

All data is stored in a database.  By default, it is located in
B<./p0rn.db> (yes, that's the directory from which you're starting
p0rn-dbrestore).  If you want to change this, set the environment
variable B<P0RNDBLOCATION> (the second letter is a zero) to another
path and filename.

=head1 SEE ALSO

L<p0rn-proxy(1)>, L<p0rn-download(1)>, L<p0rn-dbdump(1)>

=head1 MODULES NEEDED

 use DBM::Deep;

This module can be obtained at <F<http://www.cpan.org>>.

=head1 BUGS

Please report bugs by mail to <F<p0rn-bugs@cgarbs.de>>.

=head1 AUTHOR

p0rn-dbrestore was written by Christian Garbs <F<mitch@cgarbs.de>>.

=head1 AVAILABILITY

Look for updates at L<http://www.cgarbs.de/p0rn-comfort.en.html>.

=head1 COPYRIGHT

p0rn-dbrestore is licensed under the GNU GPL.

=cut

my @tables = qw(thumbz picz downz);
my $db_open = 0;

while (my $line =<>) {
    chomp $line;

    # new table?
    if ($line =~ /^\?([a-z]+)\&$/) {

	my $table = $1;
	if ($db_open) {
	    close LOAD or die "can't close pipe: $!\n";
	}

	print "clearing table $table\n";
	system("p0rn-dblist $table | p0rn-dbdel $table");

	print "loading table $table\n";
	open LOAD, "| p0rn-dbadd $table" or die "can't open pipe: $!\n";
	$db_open = 1;

    } else {
	print LOAD "$line\n" if $db_open;
    }
}

if ($db_open) {
    close LOAD or die "can't close pipe: $!\n";
}

print "finished\n";
