#!/usr/bin/perl -w
# $Id: p0rn-dbdel,v 1.1 2004-05-09 10:40:24 mitch Exp $
#
# remove contents from p0rn.db
#
use strict;
use BerkeleyDB::Hash;
use P0rn::DB;

my $hash = opendb(shift);

while (my $line = <>) {
    chomp $line;
    $line =~ s/\?.*$//;
    delete $hash->{$line};
}

untie %{$hash};


