#!/usr/bin/perl -w
# $Id: p0rn-bot,v 1.1 2004-11-14 18:40:11 mitch Exp $
use strict;

use LWP::UserAgent;
use HTML::Parser;

my $in_link = 0;
my $base;
my $ua = LWP::UserAgent->new;
$ua->timeout(10);
$ua->env_proxy;
my $parser = HTML::Parser->new(api_version => 3);
$parser->handler( start => \&start_handler, "tagname,attr");
$parser->handler( end   => \&end_handler,   "tagname");

sub debug
{
    warn "@_\n";
}

sub check_image($$$)
{
    my ($img, $link, $base) = (@_);
    debug "---------";
    debug "image: $img";
    debug "link:  $link";
    if ($link) {
	debug "linked picture.";
    } else {
	debug "DOWNLOADABLE PICTURE: $base.$img";
    }
}

sub start_handler
{
    my ($tag, $attr) = (@_);
    if ($tag eq "img") {
	check_image($attr->{src}, $in_link, $base);
    } elsif ($tag eq "a") {
	$in_link = $attr->{href};
	debug $in_link;
    }
}

sub end_handler
{
    return if shift ne "a";
    $in_link = 0;
}


sub check_url
{
    my ($url, $recurse) = @_;

    return unless defined $url;
    $recurse = 0 unless defined $recurse;

    debug "GET $url";
    $base=$url;
    my $response = $ua->request(HTTP::Request->new(GET => $url),
				sub {$parser->parse($_[0])});
    
    if ($response->is_success) {
	debug "GET ok";
	
    }
}

check_url('http://www.teenhouse.ch/main.shtml');
