#!/usr/bin/perl -w
# $Id: p0rn-dbadd,v 1.1 2004-05-09 10:40:22 mitch Exp $
#
# add contents to p0rn.db
#
use strict;
use BerkeleyDB::Hash;
use P0rn::DB;

my $hash = opendb(shift);

while (my $line = <>) {
    chomp $line;
    $line =~ s/\?.*$//;
    $hash->{$line}=0;
}

untie %{$hash};


