#!/usr/bin/perl -w
# $Id: p0rn-download,v 1.4 2004-05-11 15:59:09 mitch Exp $
#
# download selected p0rn
#
use strict;
use BerkeleyDB::Hash;
use P0rn::DB;

my $wait_after_download = 10;
my $wait_after_cycle    = 30;

my $hash = opendb('downz');

my $done_something = 1;

$SIG{CHLD} = 'IGNORE';

while ($done_something) {

    $done_something = 0;
    
    foreach my $url (keys %{$hash}) {
	
	if ($hash->{$url} == 0) {

	    if (!fork()) {
		warn "[[ START $url ]]\n";
		my $myhash = opendb('downz');
		$myhash->{$url} = 1;
		untie %{$myhash};

		system('./p0rn-grab', $url);

		$myhash = opendb('downz');
		$myhash->{$url} = 2;
		untie %{$myhash};
		warn "[[ FINISHED $url ]]\n";
		exit;
	    }

	    sleep $wait_after_download;

	}

    }

    sleep $wait_after_cycle;

}

untie %{$hash};

warn "\n[[ FINISHED. ]]\n\n";
