# $1$
# p0rn-dbdump manpage
# (C) by Christian Garbs <mitch@cgarbs.de>
# Licensed under GNU GPL

=head1 NAME

p0rn-dbdump - dump the p0rn database

=head1 SYNOPSIS

B<p0rn-dbdump>

=head1 OVERVIEW

p0rn-dbdump writes the contents of to the p0rn database to STDOUT,
thus allowing to backup the database.

=head1 FILES

All data is stored in a database.  By default, it is located in
B<./p0rn.db> (yes, that's the directory from which you're starting
p0rn-dbdump).  Is you want to change this, set the environment variable
B<P0RNDBLOCATION> (the second letter is a zero) to another path and
filename.

=head1 SEE ALSO

L<p0rn-proxy(1)>, L<p0rn-download(1)>, L<p0rn-dbrestore(1)>

=head1 MODULES NEEDED

 use BerkeleyDB::Hash;

This module can be obtained at <F<http://www.cpan.org>>.

=head1 BUGS

Please report bugs by mail to <F<p0rn-bugs@cgarbs.de>>.

=head1 AUTHOR

p0rn-dbdump was written by Christian Garbs <F<mitch@cgarbs.de>>.

=head1 COPYRIGHT

p0rn-dbdump is licensed under the GNU GPL.

=cut

