#!/usr/bin/perl -w
# $Id: p0rn-bot,v 1.2 2004-11-14 18:48:39 mitch Exp $
use strict;

use LWP::UserAgent;
use HTML::Parser;

my $base;
my $ua = LWP::UserAgent->new;
$ua->timeout(10);
$ua->env_proxy;
my $parser = HTML::Parser->new(api_version => 3);
$parser->handler( start => \&start_handler, "tagname,attr");

sub debug
{
    warn "@_\n";
}

sub start_handler
{
    return unless shift eq "a";
    my $attr = shift;
    my $link = $attr->{href};

    return if ($link =~ /^javascript:/);
    $link = $base . $link unless $link =~ m,^http://,;

    debug $link;
}

sub parse_page($)
{
    my $response = shift;

    $base = $response->base;
    $parser->parse($response->content);
}

sub check_url
{
    my ($url, $recurse) = @_;

    return unless defined $url;
    $recurse = 0 unless defined $recurse;

    debug "GET $url";
    my $response = $ua->get($url);

    if ($response->is_success) {
	debug "GET ok";
	parse_page $response;
	
    }
}

check_url('http://www.teenhouse.ch/main.shtml');
