#!/usr/bin/perl -w
# $Id: p0rn-dblist,v 1.1 2004-05-09 10:40:28 mitch Exp $
#
# dump contents from p0rn.db
#
use strict;
use BerkeleyDB::Hash;
use P0rn::DB;

my $hash = opendb(shift);

print "$_\n" foreach (sort keys %{$hash});

untie %{$hash};


